const fs = require('fs');
const path = require('path');

const dirs = [
  'src/styles',
  'src/assets/icons',
  'data/patterns',
  'data/rules',
  'dist'
];

dirs.forEach(dir => {
  const fullPath = path.join(__dirname, '..', dir);
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true });
    console.log(`Created: ${dir}`);
  }
});

// Create initial output.css if it doesn't exist
const outputCss = path.join(__dirname, '..', 'src/styles/output.css');
if (!fs.existsSync(outputCss)) {
  fs.writeFileSync(outputCss, '/* Generated by Tailwind CSS */');
  console.log('Created: src/styles/output.css');
}

console.log('Setup complete!');